### ISSUE TITLE
Unable to find chapter 6 code

### ISSUE THREAD

**Issue by rcse2006** [DOsinga/deep_learning_cookbook#11]
Hi,
Unable to find chapter 6 code for Question Matching project. Can you please update complete code of chapter  6.

Thanks,
Rama

**Comment by DOsinga** [comment]
Hmm, I think something went wrong here indeed. 5.1 exists twice!

+1 929 247 6036 | GMT-4 | douwe.osinga@gmail.com

**Comment by WillKoehrsen** [comment]
It looks like Notebook:  `05.1 Generating Text in the Style of an Example Text.ipynb` is really the notebook for chapter 6. 

Notebook: `06.1 Generating text in the style of an example texts.ipynb` is really the notebook for Chapter 5. 

A simple renaming should solve the issue.

**Comment by DOsinga** [comment]
Oh, thanks. Good catch!
