### ISSUE TITLE
How to import nb_utils

### ISSUE THREAD

**Issue by egglang** [DOsinga/deep_learning_cookbook#13]
07.1 Text Classification and 07.2 Emoji Suggestions are trying to import **nb_utils**, but the nb_utils isn't a standard python module. 
I'd like to know how I can get this. It's maybe **from keras.utils** ?

Thanks,

**Comment by DOsinga** [comment]
Sorry about that. I deleted this file thinking we were no longer referring to it. I really need to rerun everything. I am travelling right now, but put back a version that I had locally. Can you give that a spin? i..e refetch the repository and it should import locally.

**Comment by egglang** [comment]
It seems to work well. I appreciate your prompt response!
