### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by p8R** [DOsinga/deep_learning_cookbook#31]
In the recipe 16.9 you mention keras_js directory and nietzsche.html web page, both should be included in repository, both are missing! Could you add them to the repo, please?

**Comment by DOsinga** [comment]
I added a `keras_js` directory that should help. Please let me know if that works for you. I'll add a READ.ME later but basically you need to run something like `python2 -m SimpleHTTPServer` to try it out.

**Comment by p8R** [comment]
Thank you very much for prompt response! I will give it a try, and let you know in case of any problems.
