### ISSUE TITLE
Mac users need to install leveldb during pip install

### ISSUE THREAD

**Issue by violetwhitney** [DOsinga/deep_learning_cookbook#6]
When I was running through the install steps I ran into this error after running `pip install -r requirements.txt` command.

<img width="1677" alt="pip install error" src="https://user-images.githubusercontent.com/14256456/43994025-14adbd26-9d64-11e8-9331-c7a188b3eaec.png">

According to [this Stackoverflow post](https://stackoverflow.com/questions/26199376/how-to-install-leveldb-on-mac-os-x), it seems like my system didn't have leveldb installed. The post just recommends using Homebrew to install it: `brew install leveldb`. Then I could finish the install.

**Comment by DOsinga** [comment]
Thanks for noticing this. It sounds to me like an issue with the config for `pip install leveldb`

@rjpower - didn't you say you had said that up?

**Comment by rjpower** [comment]
We include the leveldb C++ source for the py-leveldb package, but it looks like we're using plyvel as the requirement here, and plyvel doesn't include leveldb directly.

We could switch to py-leveldb?

**Comment by a759116** [comment]
I experienced the same issue that Whitney has reported above, and did brew install leveldb. Now, I'm facing a different issue. Can you please help?

Installing collected packages: plyvel, protobuf, sklearn, spotipy, werkzeug, wheel, tensorboard, termcolor, tensorflow, tqdm
  Running setup.py install for plyvel ... error
    Complete output from command /Users/rpanda14/AI/deep_learning_cookbook/venv3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/ts/l9pzd7f16dx5chft9rmchkznb6d6vx/T/pip-install-lwea0w8t/plyvel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/ts/l9pzd7f16dx5chft9rmchkznb6d6vx/T/pip-record-07836l53/install-record.txt --single-version-externally-managed --compile --install-headers /Users/rpanda14/AI/deep_learning_cookbook/venv3/include/site/python3.6/plyvel:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/plyvel
    copying plyvel/_version.py -> build/lib.macosx-10.7-x86_64-3.6/plyvel
    copying plyvel/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/plyvel
    running build_ext
    building 'plyvel._plyvel' extension
    creating build/temp.macosx-10.7-x86_64-3.6
    creating build/temp.macosx-10.7-x86_64-3.6/plyvel
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/rpanda14/anaconda3/include -arch x86_64 -I/Users/rpanda14/anaconda3/include -arch x86_64 -I/Users/rpanda14/AI/deep_learning_cookbook/venv3/include -I/Users/rpanda14/anaconda3/include/python3.6m -c plyvel/_plyvel.cpp -o build/temp.macosx-10.7-x86_64-3.6/plyvel/_plyvel.o -Wall -g -mmacosx-version-min=10.7 -stdlib=libc++
    In file included from plyvel/_plyvel.cpp:589:
    In file included from /usr/local/include/leveldb/db.h:11:
    In file included from /usr/local/include/leveldb/iterator.h:20:
    /usr/local/include/leveldb/status.h:26:11: error: expected ';' at end of declaration list
      Status() noexcept : state_(nullptr) { }
              ^
    /usr/local/include/leveldb/status.h:32:23: error: expected ';' at end of declaration list
      Status(Status&& rhs) noexcept : state_(rhs.state_) { rhs.state_ = nullptr; }
                          ^
    /usr/local/include/leveldb/status.h:102:16: error: 'Status' is missing exception specification 'throw()'
    inline Status::Status(const Status& rhs) {
                   ^
    /usr/local/include/leveldb/status.h:23:22: note: previous declaration is here
    class LEVELDB_EXPORT Status {
                         ^
    /usr/local/include/leveldb/status.h:114:48: error: expected function body after function declarator
    inline Status& Status::operator=(Status&& rhs) noexcept {
                                                   ^
    plyvel/_plyvel.cpp:21159:125: warning: offset of on non-POD type 'struct __pyx_obj_6plyvel_7_plyvel_Iterator' [-Winvalid-offsetof]
      if (__pyx_type_6plyvel_7_plyvel_Iterator.tp_weaklistoffset == 0) __pyx_type_6plyvel_7_plyvel_Iterator.tp_weaklistoffset = offsetof(struct __pyx_obj_6plyvel_7_plyvel_Iterator, __pyx_base.__weakref__);
                                                                                                                                ^                                                    ~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/9.1.0/include/stddef.h:120:24: note: expanded from macro 'offsetof'
    #define offsetof(t, d) __builtin_offsetof(t, d)
                           ^                     ~
    1 warning and 4 errors generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by DOsinga** [comment]
This seems to be the same issue as google/leveldb#637 - the source of leveldb. Unfortunately the suggestion there is to change the flags to the c++ compiler, which hardly seems an option in your case. Let me see if I can reproduce this.

**Comment by a759116** [comment]
@DOsinga Thanks for your prompt response. I will wait for your update.

**Comment by shuanang** [comment]
I had two errors while running the installation command as well: 
"python setup.py egg_info" failed with error code 1
and  
Can't find a local Berkeley DB installation.

Managed to solve it by:
> brew install berkeley-db@4
> BERKELEYDB_DIR=/usr/local/Cellar/berkeley-db\@4/4.8.30/ pip install scrapy-deltafetch
> brew uninstall leveldb
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/86c8b39428a4e485e8afcc02f2e31da9d53007a0/Formula/leveldb.rb
> sudo BERKELEYDB_DIR=/usr/local/Cellar/berkeley-db\@4/4.8.30/ pip3 install -r requirements.txt
