### ISSUE TITLE
14.3 Icon GAN: 'Model' object has no attribute 'inbound_nodes'

### ISSUE THREAD

**Issue by greatspacehero** [DOsinga/deep_learning_cookbook#60]
Notebook 14.3. Icon GAN
execution of def gan(g, d) / def get_internal_updates(model) fails with error _'Model' object has no attribute 'inbound_nodes'_
<img width="743" alt="14_3_inbound_nodes_error" src="https://user-images.githubusercontent.com/51802311/59467255-82c3fc00-8e2f-11e9-933a-5e3733bef746.png">

**Comment by greatspacehero** [comment]
inbound_nodes was renamed to _inbound_nodes (added underscore). Issue closed

**Comment by DOsinga** [comment]
Thanks. I was just looking at this: https://stackoverflow.com/questions/48329150/keras-inputlayer-object-has-no-attribute-inbound-nodes-when-converting-to-cor
