### ISSUE TITLE
Cannot run the first command to run the code 

### ISSUE THREAD

**Issue by DylanDan** [DOsinga/deep_learning_cookbook#61]
os: centos7 64bit
when i run the command first time which mentioned in the book as :
source venv3/bin/activate
 jupyter notebook
i encountered the issue like:
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/code/deep_learning_cookbook/venv3/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/home/code/deep_learning_cookbook/venv3/lib/python3.7/site-packages/notebook/notebookapp.py", line 86, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/code/deep_learning_cookbook/venv3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by DOsinga** [comment]
Hi,

Did you per chance overlook the line to install the dependencies?

![image](https://user-images.githubusercontent.com/952558/59725424-a1ddd780-91fb-11e9-8f65-0c395595418e.png)

**Comment by DylanDan** [comment]
Thanks!
fixed it, as my os lack the lib:sqlite-devel
after installing this and re- install the python3, it works well. and still have a quesion: what the env you suggest to run your program, Linux or windows?

**Comment by DOsinga** [comment]
Linux, for sure. I've worked on this on OSX and Linux and it *should* work, but to be honest, dependencies even with pip are still often a mess when it comes to external libraries. On Windows this seems worse since a lot of wheels don't have the right libraries for Windows.

**Comment by DylanDan** [comment]
Thanks again! i use centos7 64bit to run your code. very nice
