### ISSUE TITLE
Jupyter notebook 03.1 raises ValueError: not enough values to unpack,( expected 2 got 0)

### ISSUE THREAD

**Issue by Rexfarell** [DOsinga/deep_learning_cookbook#65]
What really puzzles me is that the first time I ran this notebook it worked fine. Then, five minutes later or less, I reran it and it never worked ever since. I did not change anything in the environment that I know of. 

Could you please point me in the right direction with this issue? 

![image](https://user-images.githubusercontent.com/42093317/68636947-8e336480-0540-11ea-92fb-2945d970c333.png)

**Comment by DOsinga** [comment]
That's very strange. The only thing I can imagine is that somehow the downloaded file got corrupted. Try deleting it and re-downloading it maybe?

**Comment by Rexfarell** [comment]
Thank you for your quick reply. I will reclone the whole repository then.
By the way, I am enjoying your book very much.

**Comment by DOsinga** [comment]
That's great to hear about the book! I don't think you need to re-clone the repository, if you just print the `unzipped` variable and delete whatever file it says there, you should be good. Or even just change the value of `MODEL`
