### ISSUE TITLE
Tensorflow and Python runtime version incompatability

### ISSUE THREAD

**Issue by violetwhitney** [DOsinga/deep_learning_cookbook#7]
When running through the first exercise I ran into a Python runtime error with Python 3.6, saying that the tensorflow fast_tensor_util version 3.5 package wasn't compatible.

<img width="1614" alt="screen shot 2018-08-11 at 11 57 02 am" src="https://user-images.githubusercontent.com/14256456/43994108-5ccc18b8-9d65-11e8-91c3-2c7b06498c4b.png">

I was able to fix this error by installing Python 3.5.5 instead and running through the install steps again. I think the book intro says Python 3 rather than saying Python 3.5 is specifically required.

**Comment by violetwhitney** [comment]
10.13.5

**Comment by DOsinga** [comment]
Seems like a tensorflow problem with a workaround now. Sorry! Closing.
