### ISSUE TITLE
Exercise 03.1 file not found

### ISSUE THREAD

**Issue by violetwhitney** [DOsinga/deep_learning_cookbook#8]
On exercise 03.1 when downloading the pretrained model from Google News, I ran into a FileNotFound error:

<img width="1680" alt="screen shot 2018-08-11 at 12 41 05 pm" src="https://user-images.githubusercontent.com/14256456/43994215-52986836-9d67-11e8-8e76-39fc0c093310.png">

I was able to fix this by creating a folder named "generated" in the "deep_learning_cookbook" folder.

I wonder if manually making a new folder is the right solution or if its better to make a new folder with the code.

**Comment by DOsinga** [comment]
Good catch. I made a change in the notebook that should fix this.
