### ISSUE TITLE
Unable to see exercise 8.4 Training a seq2seq Chatbot code

### ISSUE THREAD

**Issue by rcse2006** [DOsinga/deep_learning_cookbook#9]
Unable to see code for exercise 8.4 Training a seq2seq Chatbot.

**Comment by DOsinga** [comment]
Odd. Something must have gone wrong. I'll look around to see where that thing went.

**Comment by DOsinga** [comment]
Ok, I checked. There is not notebook for this section, since this is part of the seq2seq code from Google, which is hard to run from a notebook. Would it help if I put together a script instead?

**Comment by rcse2006** [comment]
Yes, sure
